import { getZonePoint } from "../../domain/zones";
import type { OffenseId, PlayAction, PlayDocument, Point } from "../../domain/types";
import { actionEndSecond } from "../time/seconds";
import { possessionEvents } from "../validation/validatePlay";
import { interpolatePath, interpolateStraight } from "./pathInterpolation";
import { getPlayerPositionAt } from "./playerPositions";
export interface BallState { position: Point; ownerId?: OffenseId; phase: "held" | "passing" | "shooting" | "at_rim"; actionId?: string; }
function ownerAt(document: PlayDocument, second: number): OffenseId { let owner = document.ballOwnerId; const valid = new Set<string>(); for (const event of possessionEvents(document)) { if (event.time > second) break; if (event.kind === "pass_start" && event.action.actorId === owner) valid.add(event.action.id); if (event.kind === "pass_complete" && valid.has(event.action.id)) if (event.action.type === "pass") owner = event.action.targetPlayerId; } return owner; }
export function getBallStateAt(document: PlayDocument, second: number): BallState { const passes = document.actions.filter((a): a is Extract<PlayAction,{type:"pass"}> => a.type === "pass"); const activePass = passes.find((a) => second >= a.startSecond && second < actionEndSecond(a)); if (activePass) return { position: interpolateStraight(getPlayerPositionAt(document, activePass.actorId, activePass.startSecond), getPlayerPositionAt(document, activePass.targetPlayerId, actionEndSecond(activePass)), (second - activePass.startSecond) / activePass.durationSecond), phase: "passing", actionId: activePass.id }; const shots = document.actions.filter((a): a is Extract<PlayAction,{type:"shot"}> => a.type === "shot"); const activeShot = shots.find((a) => second >= a.startSecond && second < actionEndSecond(a)); if (activeShot) return { position: interpolatePath(getPlayerPositionAt(document, activeShot.actorId, activeShot.startSecond), getZonePoint("rim"), (second - activeShot.startSecond) / activeShot.durationSecond, undefined, true), phase: "shooting", actionId: activeShot.id }; const finishedShot = shots.find((a) => second >= actionEndSecond(a)); if (finishedShot) return { position: getZonePoint("rim"), phase: "at_rim", actionId: finishedShot.id }; const owner = ownerAt(document, second); return { position: getPlayerPositionAt(document, owner, second), ownerId: owner, phase: "held" }; }
