import { z } from "zod";
import { metadataFor, COACH_UI, type CommandIdentity } from "./commandMetadata";
import { ExpectedCommandError, commandFailure, type CommandResult } from "./commandResults";
import { appendActivityEvent, deterministicCommandDependencies, type CommandDependencies } from "./transaction";
import { validatePlay } from "../engine/validation";
import { getPlayDuration } from "../engine/animation/playerPositions";
import type { PlayStore } from "../state/playStore";
import type { ValidationReport } from "../domain/types";
import type { AnimationController } from "../engine/animation/animationController";

export interface SessionDependencies extends CommandDependencies { animationController?: AnimationController; }
export interface StartAnimationInput { speed?: 0.5 | 1 | 1.5 | 2; loop?: boolean; }
const startSchema = z.object({ speed: z.union([z.literal(0.5), z.literal(1), z.literal(1.5), z.literal(2)]).optional(), loop: z.boolean().optional() }).strict();
export interface SessionCommands { runValidation: (identity?: CommandIdentity) => CommandResult<Extract<ValidationReport, { status: "complete" }>>; startAnimation: (input?: StartAnimationInput, identity?: CommandIdentity) => CommandResult<{ status: "playing"; durationSeconds: number; speed: 0.5 | 1 | 1.5 | 2; loop: boolean; validation: { valid: boolean; errors: number; warnings: number } }>; pauseAnimation: () => void; resumeAnimation: () => void; restartAnimation: (input?: StartAnimationInput, identity?: CommandIdentity) => CommandResult<{ status: "playing"; durationSeconds: number; speed: 0.5 | 1 | 1.5 | 2; loop: boolean; validation: { valid: boolean; errors: number; warnings: number } }>; setAnimationSpeed: (speed: 0.5 | 1 | 1.5 | 2) => void; setAnimationLoop: (loop: boolean) => void; stopAnimation: () => void; }
function reportForCurrentDocument(store: PlayStore): Extract<ValidationReport, { status: "complete" }> { const report = validatePlay(store.getState().document); store.getState().updateSession((session) => ({ ...session, validation: report })); return report; }
export function refreshSessionAfterContentMutation(store: PlayStore): void { const state = store.getState(); state.updateSession((session) => ({ ...session, animation: { ...session.animation, status: "idle", currentSecond: 0 }, validation: session.validation.status === "complete" ? validatePlay(state.document) : session.validation })); }
export function createSessionCommands(store: PlayStore, dependencies: SessionDependencies = deterministicCommandDependencies): SessionCommands { const activity = (operation: string, identity: CommandIdentity, summary: string, status: "completed" | "failed") => { const revision = store.getState().document.playRevision; appendActivityEvent(store, dependencies, { ...metadataFor(operation, identity), summary, revisionBefore: revision, revisionAfter: revision, status }); };
  const start = (raw: StartAnimationInput = {}, identity: CommandIdentity = COACH_UI, fromStart = true): CommandResult<{ status: "playing"; durationSeconds: number; speed: 0.5 | 1 | 1.5 | 2; loop: boolean; validation: { valid: boolean; errors: number; warnings: number } }> => { const revision = store.getState().document.playRevision; try { const input = startSchema.parse(raw); const current = store.getState().session.validation; const validation: Extract<ValidationReport, { status: "complete" }> = current.status === "complete" && current.validatedRevision === revision ? current : reportForCurrentDocument(store); const durationSeconds = getPlayDuration(store.getState().document); if (!validation.valid || durationSeconds <= 0) { const errors = validation.errors.slice(0, 4); const error = new ExpectedCommandError("PLAY_INVALID", !validation.valid ? "The play has blocking validation errors. Repair the play before animating." : "The play needs at least one timed action before it can animate.", { validationErrorCount: validation.errors.length, errors }); activity("animate_play", identity, error.message, "failed"); return commandFailure(revision, error); }
    const speed = input.speed ?? 1; const loop = input.loop ?? false; store.getState().updateSession((session) => ({ ...session, animation: { status: "playing", currentSecond: fromStart ? 0 : session.animation.currentSecond, speed, loop } })); dependencies.animationController?.start(fromStart); const data = { status: "playing" as const, durationSeconds, speed, loop, validation: { valid: true, errors: 0, warnings: validation.warnings.length } }; activity("animate_play", identity, `Animation started for ${durationSeconds} seconds.`, "completed"); return { ok: true, revision, data, validation: { errors: 0, warnings: validation.warnings.length } };
  } catch (error: unknown) { if (error instanceof z.ZodError) { const result = new ExpectedCommandError("INVALID_INPUT", "The animation input is invalid.", error.issues); activity("animate_play", identity, result.message, "failed"); return commandFailure(revision, result); } throw error; } };
  return { runValidation: (identity = COACH_UI) => { const report = reportForCurrentDocument(store); activity("validate_play", identity, report.valid ? `Validated the play: ${report.checksPassed}/${report.checksTotal} checks passed.` : `Validated the play: ${report.errors.length} error${report.errors.length === 1 ? "" : "s"} across ${report.checksTotal} checks.`, "completed"); return { ok: true, revision: store.getState().document.playRevision, data: report, validation: { errors: report.errors.length, warnings: report.warnings.length } }; }, startAnimation: (input = {}, identity = COACH_UI) => start(input, identity), restartAnimation: (input = {}, identity = COACH_UI) => start(input, identity, true), pauseAnimation: () => { dependencies.animationController?.cancel(); store.getState().updateSession((session) => ({ ...session, animation: { ...session.animation, status: "paused" } })); }, resumeAnimation: () => { store.getState().updateSession((session) => ({ ...session, animation: { ...session.animation, status: "playing" } })); dependencies.animationController?.start(); }, setAnimationSpeed: (speed) => store.getState().updateSession((session) => ({ ...session, animation: { ...session.animation, speed } })), setAnimationLoop: (loop) => store.getState().updateSession((session) => ({ ...session, animation: { ...session.animation, loop } })), stopAnimation: () => { dependencies.animationController?.cancel(); store.getState().updateSession((session) => ({ ...session, animation: { ...session.animation, status: "idle", currentSecond: 0 } })); } }; }
